# Generated by Django 5.2.3 on 2025-06-24 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the car make (e.g., 'Ford', 'Toyota').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the car make.')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the car model (e.g., 'Focus', 'Camry').", max_length=100)),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('COUPE', 'Coupe'), ('SPORTS', 'Sports Car'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('ELECTRIC', 'Electric Vehicle'), ('HYBRID', 'Hybrid Vehicle'), ('LUXURY', 'Luxury Car'), ('OTHER', 'Other')], default='SEDAN', help_text="The type of car (e.g., 'SUV', 'Sedan').", max_length=20)),
                ('year', models.IntegerField(help_text='The manufacturing year of the car model.')),
                ('carmake', models.ForeignKey(default=1, help_text='The car make this model belongs to.', on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake')),
            ],
            options={
                'unique_together': {('carmake', 'name', 'year')},
            },
        ),
    ]
